### ISSUE TITLE
Update the NATS dependency package and set the ping timeout to a reasonable value.

### ISSUE THREAD

**Issue by ghost** [cloudfoundry/gunk#5]
Currently if the NATS client loses contact with the server it initially connected to, then it could take a couple of minutes before the route connects to a new NATS. This is because it waits 2 minutes before it tries to receive a valid pin/pong health check message and it waits for 2 of these to fail before attempting to reconnect. This means that gorouter could start dropping the routes sent from route-emitter.

If the NATS dependency is updated to use the new [repo](https://github.com/nats-io/nats) then a "PingInterval" can be set on the NATS connection. On the RuntimeOG team we have been hardcoding things to "30s". Which is just a number reasonably lower than the router's route timeout interval.

This update should hopefully minimize any network outages where a NATS vm is affected.

**Comment by ematpl** [comment]
Thanks, @DanLavine, sounds reasonable. Since you have context on the require changes, would you or the rest of the Runtime OG team be willing to provide a PR?

Best,
Eric

**Comment by DanLavine** [comment]
@ematpl,

This one change would require a number of PRs, at least gunk and route-emitter. Then diego-release could hopefully bump go-router (they already use `nats-io/nats`) and remove `apcera/nats`. However it might be used in other places, didn't go through the whole stack.

So we figured it would be easiest to just let diego do all the changes at once rather than coordinate a whole bunch of PRs.

Dan

**Comment by ematpl** [comment]
Cool, sounds like a good opportunity to clean up some of those repos and dependencies.

**Comment by emalm** [comment]
Closing, as the Diego team did this.
